### ISSUE TITLE
JavaScript - holdAnimClass

### ISSUE THREAD

**Issue by sofar0cka** [anijs/anijs#47]
I love AniJS :) i have a question about this:

AniJS.createAnimation([{
    event: 'click',  //if
    eventTarget: '.animated1',  //on
    behavior: 'hinge bounceIn animated', //do
    behaviorTarget: '.animated1target', //to
    after: 'holdAnimClass',
}]);

The after: 'holdAnimClass' didn´t work for me. How can i get this work?

Cheers
Tobi

**Comment by darielnoel** [comment]
Hi, thank you very much. I take a look to your question, The reason is because we change this behavior since [0.9.0](https://github.com/anijs/anijs/releases/tag/v0.9.0) version and not update the documentation. I am really sorry :(. Thanks to you we going to update the documentation of this today.

- If you want to hold the animation class you don't have to do anything.

Look at  [this](https://github.com/anijs/anijs/wiki/Remove-animation-after-function#hold-animation-class)

- if you **don't want** to execute the animation again.

Look at  [this](https://github.com/anijs/anijs/wiki/Remove-animation-after-function#remove-the-event-that-triggers-the-animation)

- Remove the animation class.
Look at  [this](https://github.com/anijs/anijs/wiki/Remove-animation-after-function#remove-the-animation-class)

Please write me back if you have any trouble with this. Thanks in advance :)

Best Regards, Dariel

**Comment by sofar0cka** [comment]
If tried but it didn´t work for me. I need to manipulate the elements via Javascript, thats because i need this:

AniJS.createAnimation([{
event: 'click', //if
eventTarget: '.animated1', //on
behavior: 'hinge bounceIn animated', //do
behaviorTarget: '.animated1target', //to
after: $fireOnce,
}]);

Is this correct? I have tried this too(after: '$fireOne',)

Thanks for your help :)

**Comment by darielnoel** [comment]
I created a [pen](http://codepen.io/darielnoel/pen/vEQZNv) for you. Please take a look.

Regards :)

**Comment by sofar0cka** [comment]
I Love you :+1:  :)

One another question to this is:

how can i handle this with $remove, $clone and the others?

if i try to add these to your pen:

AniJS.createAnimation([{
event: 'click', //if
eventTarget: '.animated1', //on
behavior: 'hinge bounceIn animated', //do
behaviorTarget: '.animated1target', //to
after: 'clone .animated1target',
}]);

It isn´t working too :( The same with remove, add etc.)

Thank you for you great work i will support you on Kickstarter.com ;)

**Comment by darielnoel** [comment]
I am very happy that it works for you.

About the $remove, $clone and the others, you can use it right now.  We release a [new version](https://github.com/anijs/anijs/releases/tag/0.9.3) that fix the bug.

Please take a look at this [pen](http://codepen.io/darielnoel/pen/ByGmoB) to see this working. Thanks a lot for the feedback.

I will apreciatte your Kickstarter.com support ;).

Best Regards, Dariel

**Comment by sofar0cka** [comment]
Yeah!

Thats great. Really awesome.

Thank you.
