### ISSUE TITLE
[QUESTION] Deactivating AniJS on mobile?

### ISSUE THREAD

**Issue by beltranrengifo** [anijs/anijs#61]
Hi there!
I've noticed some strange behaviours on mobile with CSS animations in my project. It's really my first time using Ani, so maybe I'm missing a point.

Is there a way to deactivate all Ani data?

The link:
http://taudesign.com/temp/edelvives/inloove/presentacion/

Big thanxs!

**Comment by darielnoel** [comment]
Hi Beltrán, Wow man your work is impresive!!  

You can deactivate all the AniJS data using the [purgeAll](https://github.com/anijs/anijs/wiki/Purge-Events) function.

```javascript
    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
       AniJS.purgeAll();        
    }
```

Suggestion:

I noticed that your are using **before: scrollReveal, after: removeAnim** in the same sentence. Because of that the animations are been triggering when the user **scroll up** too. So, If this is your desired behavior Ok. But if it's not, You can just remove **after: removeAnim** in those sentences and that should work.

// execute the scrollReveal animation **just one time** when the user scroll down the page the **first time**
```javascript
data-anijs="if: scroll, on: window, do: bounceInLeft animated, before: scrollReveal"
```

// execute the scrollReveal animation **many times** using **repeat**
```javascript
data-anijs="if: scroll, on: window, do: bounceInLeft animated, before: scrollReveal repeat"
```

Best Regards, Dariel

P.S: Can I reference your presentation in our official page? That could be awesome. Thanks

**Comment by beltranrengifo** [comment]
Hi Dariel!
Thanks a lot for your comment. The impressive thing here is the work you've made with Ani and the fact you are sharing it, and helping us :)

The deactivation/purge works perfect on mobile. I did not understand properly the purge method.

It's my first project using Ani, I'm still not very well familiarized with the documentation, in fact, I did not understand properly the before, after and repeat parameters . Exactly, what I wanted is the second option:
data-anijs="if: scroll, on: window, do: bounceInLeft animated, before: scrollReveal repeat"

Anyway, the client is happy with the actual scrolling behaviour, so I'm gonna leave it this way ;)

So cool you want to reference the presentacion!! Awesome, really. Just wait till it gets on production, probably on next monday 18:00 hours (Spain). I'll let you know!

Thanks!!

**Comment by beltranrengifo** [comment]
Hi again Dariel!

The presentation is already on production.
Thanks for your help!

http://alltogethernow.edelvives.com/

**Comment by darielnoel** [comment]
It's a pleasure. Good luck ;)

**Comment by iocouto** [comment]
@darielnoel if the example you provided of how to deactivate Ani.js on mobile is still valid, perhaps it can be added to the Docs?

And then, perhaps this issue could be closed - it seems it was solved a very long time ago!
