### ISSUE TITLE
Make an animation before url redirection

### ISSUE THREAD

**Issue by jlantunes** [anijs/anijs#69]
Hello,

Anijs was an incredible discovery for me! This library is just awesome !!! But now I'm with a problem that limit really my ideas, the possibility to make an animation before a url redirection. After looking on the web I dont find any answer...

So, is there a way to start an animation before an url redirection with anijs ?

Thanks !

**Comment by darielnoel** [comment]
Hi, Thank you very much, Could you give me more details about this? What's triggering the redirection? A javascript function,  a link, or another?

Best, Dariel

**Comment by Zapow** [comment]
Hi, 
It is true that I didn't give too much information, sorry ... 
The idea would be to trigger an animation as soon as the user clicks on a link href (<a href = "https //: mylink.com / Otherpage ") leading to another page.

The problem is it returns directly to the page before you can even see the animation. So the goal would be to wait until the end of the animation before the redirection. 

Some example : http://www.fantasy.co/work/microsoft-touch (when you click on the return button)

I'm not very strong on js programation, for this I chose your library that permit to do much things simply ! :) But in jquery I did this like this, and it work :
 
`$(".button").click(function(event){
  				

  				var lien = $('#element').attr('href'); // 
  				event.preventDefault(); // Annul the normal redirection of <a> link on click

  				$("#element").animate({

  					backgroundColor : 'red'


  				}, {
  					queue: true,
  					duration: 300,
					complete : function(){
						setTimeout(function(){
							window.location.href=lien; // do the redirection after the animation was completed
						});


					}


				

				});


			}); `

PS : Sorry if my English is wrong, my level in this langage is not very good !! (French guys are so bad in this ^^)

Thanks for your patience and help ;) 
Loïc

**Comment by Zapow** [comment]
Hi, someone have any idea to do this directly with Anijs ?  Thanks

**Comment by Zapow** [comment]
Hi, finally I managed to do what I wanted, using 'after' and 'before'.
First I wrote the function which will have to cancel the redirection of the url before the animation, and after the function that will have to reactivate the redirection after the animation. Here is the jQuery code : `$(function() {
    				
    				//Obtaining the default helper
					var animationHelper = AniJS.getHelper();
					
					//Defining the prevent default to cancel the url redirection
					animationHelper.offRedirection = function(e, animationContext){
					    
						console.log('BEFOOOOORE');
						
						e.preventDefault();
						animationContext.run();

						
					}

					//Defining a redirection 
					animationHelper.doRedirection = function(e, animationContext){
					    
						console.log('AFTERRR');

						var target = e.target;//Select the element target 
						var lien = $(target).attr('href');//Select the href of target
						window.location.href=lien;//Redirection

					}



  				});`
And after the Html code of the element : `<a href="index2.html" data-anijs="if: click, do: flipInY animated, before:offRedirection, after: doRedirection"></a>`
It works perfectly ! :)

**Comment by darielnoel** [comment]
@Zapow Wow, you rocks!!! I have not had to much time ultimately. But, that's the correct approach to follow.

Thanks for sharing, Best Dariel

**Comment by Zapow** [comment]
Hey, no problem for your lack of time, I understand, and it's nice to train me to find solutions  ^^ 

However there is a new problem that I can't solve, but with time I will find, I think ... The code above works very well, but when I decide to put a parameter "to : .oneClass" which refers to several divs, the redirection of the url does not work. 

The problem is that in my second function "doRedirection", the "var target = e.target;" select all the divs which have the class ("to : .oneClass"), whereas I would like to select only the div that received the event click ("if: click"). So, if you would have an indication to help me ... how to recover the url of the div that receive the event "if: click"?

I don't know if my explanation is clear, sorry if not ^^
Thanks

**Comment by darielnoel** [comment]
Hey friend,

You should be able to solve this using: **animationContext.eventTarget**

```
var target = animationContext.eventTarget;

var lien = $(target).attr('href');//Select the href of target
window.location.href=lien;//Redirection
```

I made this quick example for you:

http://codepen.io/anon/pen/OWvOJQ

I hope this helps you ;)..., if not let me know.

Best, Dariel

**Comment by Zapow** [comment]
Hello, sorry for the delay in reply, this time it's me who was with lack of time !! ^^ 
Thank you very much for yours indications, it works very well :)

I am sorry to bother you again but I have an other problem again : 
If I use an "if: load, on: window, do: bounceOutLeft;", this work but during the loading page there is a time where we see the object loading before the animation start. This create a bad sensation of bug :/ 

I don't know if it's a conflict with the script than we write here, for this I don't create an other request, thanks !
